### ISSUE TITLE
Document / expose / publish nebula.maven-developer

### ISSUE THREAD

**Issue by devinrsmith** [nebula-plugins/nebula-publishing-plugin#118]
It looks like `nebula.maven-developer` is not documented in the README.md, nor published. It looks like it might be missing from `build.gradle`'s `pluginBundle.plugins` section? 

https://plugins.gradle.org/plugin/nebula.maven-developer

**Comment by rpalcolea** [comment]
Hi! thanks for reporting this and for the late response.

This is now documented in the README.md and also published https://plugins.gradle.org/plugin/nebula.maven-developer
