### ISSUE TITLE
[Question] How does one use this with a Spinnaker project to deploy to Artifactory

### ISSUE THREAD

**Issue by fieldju** [nebula-plugins/nebula-publishing-plugin#124]
In Spinnaker/Kayenta there is a [Gradle init script](https://github.com/spinnaker/kayenta/blob/master/gradle/init-publish.gradle) that can be used to deploy to mavenLocal decently easy.

```
./gradlew -I gradle/init-publish.gradle publishToMavenLocal -Prelease.version=1.0.29-SNAPSHOT
```

I am trying to figure out how I can configure an init-script to allow me to also publish to an internal Artifactory instance.

Any thoughts would be super helpful.

Cheers,

Justin

**Comment by chali** [comment]
Hi Justin, do you have any particular reasons why you would like to publish to internal artifactory? 

You would need to configure artifactory plugin within the init script. Here is documentation for the plugin https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin The important part is which publications from gradle should be deployed. Kayenta is using our publishing plugin which configures them. We have `nebula` (maven) and `nebulaIvy` (ivy)

**Comment by fieldju** [comment]
> Hi Justin, do you have any particular reasons why you would like to publish to internal artifactory?

Very valid question, I use Spinnaker/Kayenta as a standalone API, I would like the ability to publish hotfixes and use them while waiting for PRs to be merged and released. 

I just want to occasionally, hopefully not very often publish a snapshot and use that while I wait for the official release.

> You would need to configure artifactory plugin within the init script. Here is documentation for the plugin https://www.jfrog.com/confluence/display/RTF/Gradle+Artifactory+Plugin The important part is which publications from gradle should be deployed. Kayenta is using our publishing plugin which configures them. We have nebula (maven) and nebulaIvy (ivy)

I will take a look, thanks.
