### ISSUE TITLE
nebula-publishing-plugin version is compatible with Gradle 6.3

### ISSUE THREAD

**Issue by ramakrishnakaushik97** [nebula-plugins/nebula-publishing-plugin#169]
which nebula-publishing-plugin version is compatible with Gradle 6.3 ?
Can you please provide the compatibility matrix

**Comment by chali** [comment]
Hi @ramakrishnakaushik97, you can find compatibility requirements in release notes.

> Note: This is a breaking change and requires Gradle 6.+

E.g. https://github.com/nebula-plugins/nebula-publishing-plugin/releases/tag/v17.0.0

Anything higher than 17.0.0 will have the same requirement.
