### ISSUE TITLE
Incompatibility with gradle-extra-configurations-plugin

### ISSUE THREAD

**Issue by dnault** [nebula-plugins/nebula-publishing-plugin#30]
The `publish` task fails with NPE if there is a `provided` dependency.

Gradle 2.2.1
nebula-publishing-plugin 2.0.1
gradle-extra-configurations-plugin 2.0.1
    
    Execution failed for task ':generatePomFileForMavenNebulaPublication'.
        > Could not apply withXml() to generated POM
           > Cannot invoke method get() on null object

**Comment by dnault** [comment]
minimal build script demonstrating issue:

https://gist.github.com/dnault/5240f129d6d6aab77c46

**Comment by bmuschko** [comment]
There are dedicated releases for Gradle 2.2.x now for both plugins. Do me a favor and try those. I am not even sure if they both work together.

BTW: You might not need the publishing plugin at all. The gradle-extra-configurations-plugin not only adds the `provided` configuration but also hooks into publishing to handle it properly if that's your main use case.

**Comment by dnault** [comment]
Issue is also reproducible with version 2.2.0 of both plugins.

Thanks for the tip about gradle-extra-configurations-plugin hooking into publishing! I'd still like to use the other features of nebula-publishing-plugin though, since it addresses several issues with the built-in publishing plugin.

**Comment by bmuschko** [comment]
The publishing plugin hard-codes a mapping of scope to configuration in the class [ResolvedMavenPlugin](https://github.com/nebula-plugins/nebula-publishing-plugin/blob/gradle-1.12/src/main/groovy/nebula/plugin/publishing/maven/ResolvedMavenPlugin.groovy#L44).

    def scopeToConfMapping = [runtime: 'runtime', testRuntime: 'test']

The code doesn't seem to handle the case of a configuration that doesn't have a mapping. In this case `provided` which comes from a different plugin. This plugin should probably ignore configurations that aren't registered in the mapping. The assumption would be that handling code comes from somewhere else.

Probably in the long run the publishing plugin should integrate well with the extra-configurations plugin.

**Comment by bmuschko** [comment]
@dnault Would you be interested in providing a pull request for this?

**Comment by dnault** [comment]
@bmuschko Sure, I will take a stab at it. Thanks!

**Comment by dnault** [comment]
A workaround is to apply the `nebula.provided-base` plugin *after* `nebula.nebula-maven-publishing`.
