### ISSUE TITLE
Feature request: fix up 'runtime' dependency scopes in POM

### ISSUE THREAD

**Issue by dnault** [nebula-plugins/nebula-publishing-plugin#31]
The POM generated by the built-in maven-publish plugin declares `compile` dependencies to have `runtime` scope, even though `compile` scope is almost always more appropriate. Discussion here:

http://forums.gradle.org/gradle/topics/maven_publish_plugin_generated_pom_making_dependency_scope_runtime

It would be nice if `nebula-maven-publishing` could address this shortcoming of the built-in plugin, and patch the POM so `compile` dependencies have `compile` scope.

**Comment by rspieldenner** [comment]
So in general I'm fine with not adding my compile time dependencies to everybody who depends on me's compile time dependencies. People downstream shouldn't care.

If I'm using a dependency on my api it should be on compile in the pom. So I'd rather add a new scope that differentiates things that I need to compile that you shouldn't need to care about and things that you do.

**Comment by rspieldenner** [comment]
So anybody, thoughts on adding an api configuration that acts like compile but ends up in the pom compile scope?

**Comment by quidryan** [comment]
I'd expect something with an additional configurations:

    dependencies {
        compile 'com.google.guava:guava:18.0' // goes to runtime in pom, available in our compile classpath
        compilePublic 'commons-codec:commons-codec:1.10' // goes to compile in pom and into gradle compile configuration
        runtime 'commons-lang:commons-lang:2.6' // goes to runtime in pom
    }

**Comment by brharrington** [comment]
This issue keeps coming up, most recently https://github.com/Netflix/archaius/issues/379. It doesn't seem very desirable to keep propagating the workaround used for hystrix and listed on the readme to this project.

I like the idea of being able to explicitly specify which dependencies are part of the public api. Is addressing this on the roadmap at all?

**Comment by rspieldenner** [comment]
We don't have it scheduled right now. But can add it to the todos.

Not a lot of work to add this, but we have higher priorities currently.

**Comment by dajester2013** [comment]
Someone has posted a possible fix here: https://discuss.gradle.org/t/maven-publish-plugin-generated-pom-making-dependency-scope-runtime/7494/6

**Comment by rspieldenner** [comment]
So that's way to permissive you only want to put things in compile if your
consumer need it to compile

**Comment by rspieldenner** [comment]
Added `nebula.compile-api` plugin to add new configuration to put needed jars in compile scope
