### ISSUE TITLE
Signing for maven central

### ISSUE THREAD

**Issue by noseglid** [nebula-plugins/nebula-publishing-plugin#61]
I'm trying to setup publishing to a [nexus](http://www.sonatype.com/nexus-repository-oss) (which is a maven repository) instance I have.

I cannot use the `Maven` plugin, because the server uses [SNI](https://en.wikipedia.org/wiki/Server_Name_Indication) - which is not supported by that plugin (or rather the HTTP client it uses).

I cannot use the `maven-publish` plugin because it does not support signing the artifacts (but do support SNI!).

So I found [this thread on the gradle forums](https://discuss.gradle.org/t/how-to-publish-artifacts-signatures-asc-files-using-maven-publish-plugin/7422) where it claimed to use this plugin successfully, however it seems as if the signing capabilities were removed in c95bd26e2fdce91bde1f32af691fd7d6380b9cf1.

Do you not plan to support signing and publishing to maven repositories, or do you have another solution?

**Comment by rspieldenner** [comment]
we publish to bintray, have it sign our artifacts, and sync with
mavencentral. Internally we use artifactory and don't publish maven style
artifacts (we do ivy internally)

if you want to contribute a signing plugin to the publishing suite we'd be
open to it

**Comment by noseglid** [comment]
What happened to the signing plugin which existed until c95bd26?

**Comment by rspieldenner** [comment]
once bintray was able to auto sign our artifacts we decided we didn't want
to maintain that part of the plugin
