### ISSUE TITLE
Have global excludes reflected in pom files

### ISSUE THREAD

**Issue by rspieldenner** [nebula-plugins/nebula-publishing-plugin#65]
Go through and add the global excludes to the direct dependencies that bring in the excluded libraries.

**Comment by rpalcolea** [comment]
My assumption on this one is that when you have something like

```
configurations.all {
        exclude group: 'javax.jms', module: 'jms'
        exclude group: 'com.sun.jdmk', module: 'jmxtools'
        exclude group: 'com.sun.jmx', module: 'jmxri'
}
``` 

This will be reflected as an exclude on each dependency as Maven doesn't have a top level exclude like Ivy does.

Gradle already does that by default.

Closing this now
