### ISSUE TITLE
Gradle 3.4.1 - Support new configurations in 'java-library' within MavenResolvedDependenciesPlugin

### ISSUE THREAD

**Issue by nathklei** [nebula-plugins/nebula-publishing-plugin#72]
Since Gradle 3.4, 'java-library' adds new configurations which don't seem to get picked up when MavenResolvedDependencies resolves dependencies.  The result is that if e.g. dependency-recommender is used with java-library, the resulting POMs omit version strings.

I'm not sure the best approach here; It seems like in addition to runtime configuration the runtimeClasspath configuration needs to be appended (and maybe compileClasspath?):

https://github.com/nebula-plugins/nebula-publishing-plugin/blob/master/src/main/groovy/nebula/plugin/publishing/maven/MavenResolvedDependenciesPlugin.groovy#L42

Any advice here is appreciated! In the meantime I'll likely go back to using the old 'java' plugin

**Comment by rspieldenner** [comment]
For now use the java plugin. When we get some free time, we'll update the plugin to work with both. Hopefully this month but can't commit to that. We also welcome pull requests.

**Comment by nathklei** [comment]
Thanks for the quick reply.  Do you have any quick guidance on path forward? I'm happy to attempt a PR if it's as simple as combining runtime with runtimeClasspath!

**Comment by rspieldenner** [comment]
It would be writing a test that applies java-library and seeing what the
differences are, it might be as simple as adding another when plugin is
applied and detecting the new plugin. It might require looking at different
configs then we do now.

Example line 38 of MavenResolvedDependenciesPlugin

**Comment by nathklei** [comment]
Great, thanks.  Hopefully can take a closer look this week.

**Comment by jmcampanini** [comment]
i was able to replace that line with this:

```groovy
dependencyMap['runtime'] = project
        .sourceSets.main.runtimeClasspath.sources
        .findAll { it in Configuration }
        .collect { it.incoming.resolutionResult.allDependencies }
        .flatten()
```

and it passes all existing tests.

would this be the right approach? still need to write up a test with a `java-library` example to prove it works, but wanted to ask

**Comment by jmcampanini** [comment]
i've posted the PR that has this code in there, with a test

**Comment by mnazbro** [comment]
@rspieldenner Could we release with this fix? I'd like to be able to take advantage of java-library's configuration differences.

**Comment by jmcampanini** [comment]
@rspieldenner wondering when there would be a release so we can pick this fix up :)

**Comment by jlafourc** [comment]
Hi,

A release for that fix would be awesome ;)

Thx

Julien

**Comment by rspieldenner** [comment]
4.10.0 releasing now

**Comment by jlafourc** [comment]
I absolutely love it. Works like a charm !

Thanks again. 

Julien
